programs:
  sleeper:
    cmd: "sleep infinity"
    numprocs: 1
    autostart: true
    autorestart: never
    exitcodes:
      - 0
    startretries: 0
    starttime: 1
    stopsignal: TERM
    stoptime: 5
  printer:
    cmd: "env"
    numprocs: 2
    autostart: true
    autorestart: always
    exitcodes:
      - 0
    startretries: 0
    starttime: 1
    stopsignal: TERM
    stoptime: 5
    stdout: /tmp/printer.stdout
    env:
      STARTED_BY: taskmaster
